apiVersion: v1
kind: Service
metadata:
  namespace: kubecost
  name: kubecost-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 9090
  selector:
    app: cost-analyzer